Backend development environment setup
Free-Laborers/u-refer-backend pull request #3
Opened 2021-09-25 20:10 UTC by swjeong0825

1. Backend Setup
2. error handling

2021-09-27 16:02 UTC, dima618 requested changes

2021-09-27 16:25 UTC, swjeong0825 commented on readme.md
> +  ## PLEASE DO NOT PUSH YOUR CODE TO MAIN BRANCH DIRECTLY. ALWAYS CREATE A NEW BRANCH, DO DEVELOPMENT, AND MAKE PULL REQEST.
Oh, I didn't know that the main branch is protected. I'll update it then.

2021-09-27 16:28 UTC, swjeong0825 commented on readme.md
> +    DATABASE_URL="postgresql://<Postgres_username>:<Postgres_password>@localhost:5432/<database_name>?schema=public"
DB server and backend server will run independently. However, the connection between them is necessary for the Backend server to retrieve the data from the database server. This is required for every case no matter if you use ORM  or not.

2021-09-27 16:39 UTC, swjeong0825 commented on readme.md
> +    git pull origin backend-development-environment-setup
It is for testing.

When you clone GitHub, only the codes and files in the remote main branch will be saved as the local main branch. Since my code is currently in a separate branch instead of the main branch, we need to pull the specific branch where my code is. 

I put this because before I want to push my codes to the main branch, I want some of them to actually go through my readme instruction to see if it works. I already asked Dan to test my readme setup with his docker set-up. Once it is confirmed and we think we are good to push the readme file to the main branch, I'll remove this line at the end.

2021-09-27 23:40 UTC, dima618 commented on readme.md
> +    git pull origin backend-development-environment-setup
Gotcha, I want to get this merged by tomorrow's meeting, could you change it to what it should be in the main branch? Thanks!

2021-09-27 23:43 UTC, dima618 commented on readme.md
> +    DATABASE_URL="postgresql://<Postgres_username>:<Postgres_password>@localhost:5432/<database_name>?schema=public"
Yea so the way I see this working is we will have the docker container which will initialize the database with a specific username and password, and we will just include the .env file with those same credentials in the repo to make it easier for everyone to launch and connect stuff.

2021-09-28 03:11 UTC, swjeong0825 commented on readme.md
> +    DATABASE_URL="postgresql://<Postgres_username>:<Postgres_password>@localhost:5432/<database_name>?schema=public"
Cause all user and password is saved in a certain table in PostgreSQL if I remember correctly.

2021-09-28 03:12 UTC, swjeong0825 commented on readme.md
> +    DATABASE_URL="postgresql://<Postgres_username>:<Postgres_password>@localhost:5432/<database_name>?schema=public"
https://sharmank.medium.com/build-postgres-docker-image-with-data-included-489bd58a1f9e
Here is the link for how to send the Postgre image with the data

2021-09-28 03:12 UTC, swjeong0825 commented on readme.md
> +    git pull origin backend-development-environment-setup
Are u sure you want to just merge it without giving it a test shot?

2021-09-28 21:32 UTC, dima618 approved these changes

2021-09-28 21:32 UTC, merged